# Generated by Django 5.0.6 on 2024-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='files',
            table='events_fileslocation',
        ),
        migrations.AlterModelTable(
            name='user',
            table='events_userlocation',
        ),
    ]
