version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8000:8000
#    env_file:
#      - ./.env.dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - django_media_volume:/usr/src/app/media
#    networks:
#      - myNetwork

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - backend
#    networks:
#      - myNetwork



#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ./data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432

# migration:
#    image: uzman
#    command: python manage.py migrate --noinput
#    volumes:
#      - .:/code
#    depends_on:
#      - db


volumes:
  django_media_volume:
#  data:



#    env_file:
#      - ./.env.dev