version: '3.9'

services:
  db:
    image: postgres:13.3
    env_file: /backend/.env
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: ./backend
    container_name: backend
    restart: always
    command: >
      bash -c
        "python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
          - django_media_volume:/backend/media

  web:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000

volumes:
  django_media_volume:
  postgres_data:
